### PR TITLE
Fixes activity's related interest not populating on page load"

### LINKED ISSUE #64: Edit activity view not prefilling related interest
**Expected Behavior**
- WHEN a user elects to edit one of their activities and is redirected to `/activity/<activity_id>/edit`, THEN all fields will be pre-populated with the details of the activity

**Current Behavior**
- [x] WHEN a user is on the activity view, THEN the activity's related interest does not pre-populate the related select input.

### PR DESCRIPTION
**Pull request by jdpasternak**
closes #64

﻿- update GET /api/activities/<id> route
- includes interest in Activity.findAll under GET /api/activities/<id> route
- prefills the select option in the Related Interest dropdown with the event's related interest

### CODE REVIEW

File: controllers/api/activity-routes.js [hunk 1]
```diff
@@ -93,11 +94,12 @@ router.get("/:id", (req, res) => {
       "created_at",
       [
         sequelize.literal(
-          "(SELECT COUNT(*) FROM attending WHERE activity.id = attending.activity_id)"
+          "(SELECT COUNT(*) FROM attendance WHERE activity.id = attendance.activity_id)"
         ),
-        "attending_count",
+        "attendance_count",
```
Comment (Naomilounsbury) [inline controllers/api/activity-routes.js:99]: I put this in homeroutes as attending_count but should be a quick fix

**Review by Naomilounsbury — APPROVED** [review]
